# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.boton_detener = QtWidgets.QPushButton(self.centralwidget)
        self.boton_detener.setStyleSheet("background-color: rgb(103, 8, 8);\n"
"color: rgb(255, 255, 255);")
        self.boton_detener.setObjectName("boton_detener")
        self.gridLayout.addWidget(self.boton_detener, 3, 0, 1, 1)
        self.boton_inicio = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_inicio.sizePolicy().hasHeightForWidth())
        self.boton_inicio.setSizePolicy(sizePolicy)
        self.boton_inicio.setStyleSheet("background-color: rgb(34, 111, 22);\n"
"color: rgb(255, 255, 255);")
        self.boton_inicio.setObjectName("boton_inicio")
        self.gridLayout.addWidget(self.boton_inicio, 2, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.boton_configuracion_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_configuracion_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_configuracion_3.sizePolicy().hasHeightForWidth())
        self.boton_configuracion_3.setSizePolicy(sizePolicy)
        self.boton_configuracion_3.setStyleSheet("background-color: rgb(5, 5, 203);\n"
"color: rgb(255, 255, 255);")
        self.boton_configuracion_3.setObjectName("boton_configuracion_3")
        self.gridLayout.addWidget(self.boton_configuracion_3, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.consola_2 = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consola_2.sizePolicy().hasHeightForWidth())
        self.consola_2.setSizePolicy(sizePolicy)
        self.consola_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.consola_2.setObjectName("consola_2")
        self.verticalLayout_7.addWidget(self.consola_2)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_detener.setText(_translate("MainWindow", "Terminar conexion"))
        self.boton_inicio.setText(_translate("MainWindow", "Recibir datos"))
        self.boton_configuracion_3.setText(_translate("MainWindow", "Cambiar tamaño de ventana"))
        self.label_32.setText(_translate("MainWindow", "Consola"))
